server:
  port: 8765
spring:
  application:
    name: zuul-server
#Prefer Ip address instead of host names
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    products:
      path: /product/**
      serviceId: product-service