server:
  port: 8081

# Enabling H2 Console
spring:
  application:
    name: product-service
  h2:
  console:
    enabled: true
    path: /h2-console
  datasource:
    url:jdbc:h2: ~/product;DB_CLOSE_ON_EXIT=TRUE
    driverClassName: org.h2.Driver
    datasource:
      username: sa
      password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
